services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: fifa-tickets-db
    environment:
      POSTGRES_DB: fifa_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fifa-tickets-app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fifa_tickets
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "com.fifa-tickets.description=FIFA 2026 Ticket Management App"
      - "com.fifa-tickets.version=1.0.0"

volumes:
  postgres_data:
    driver: local